{
  "language": "python",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "python": [
    "3.6",
    "3.7",
    "3.8"
  ],
  "install": [
    "make install"
  ],
  "script": [
    "make check"
  ],
  "before_install": [
    "pip install poetry"
  ]
}
